# Use root/example as user/password credentials

services:

  db:
    image: mysql
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'Accenture'
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
volumes:
  data: